### ISSUE TITLE
Compile of BP_LansdcapeTest failed.

### ISSUE THREAD

**Issue by wildmaster84** [hippowombat/BPTerrainGen#1]
Any way to fix this for UE 4.25.4?

One or more blueprints has an unresolved compiler error, are you sure you want to Play in Editor?
BP_LansdcapeTest

Cannot use the editor function "LandscapeImportHeightmapFromRenderTarget" in this runtime Blueprint. Only for use in Editor Utility Blueprints and Blutilities.

[0036,26] Compile of BP_LansdcapeTest failed. 1 Fatal Issue(s) 0 Warning(s) [in 134 ms] (/Game/TerrainEditor/Blueprints/BP_LansdcapeTest.BP_LansdcapeTest)

**Comment by Imyamoe** [comment]
I believe it is not an issue, but rather some half-implemented functionality. All we can do now is to wait for some further dynamic landscape implementation from the Epic, unless you want to make it on your own from scratch. Also please feel free to check this thread about it: [https://forums.unrealengine.com/community/community-content-tools-and-tutorials/1557162-blueprint-powered-procedural-terrain-generation-is-now-possible-in-ue4-4-20](url)

**Comment by wildmaster84** [comment]
yea i read about that, it's how i found this. is there any working terrain generators you can recommend?

**Comment by Imyamoe** [comment]
> yea i read about that, it's how i found this. is there any working terrain generators you can recommend?

Can't really advise it since i never released any project with it yet, but as a friendly suggestion, try checking the Voxel Plugin. There is a free version available on the Marketplace. I tested it before, and it was working like a charm.
